### ISSUE TITLE
will this work for J7 J701F NXT CORE

### ISSUE THREAD

**Issue by jalalcards** [dariotrombello/android_device_samsung_j7elte#1]
Hi dear,
* I am wondering if this rom is going to work for my J7 nxt core ?
* what will I be missing if I change the rom or what problems ?
* can I root my phone with Kingroot after installing this rom ?
Thanks.

**Comment by dariotrombello** [comment]
This ROM only works on SM-J700F, SM-J700H, SM-J700M.

**Comment by jalalcards** [comment]
can you assist me where can I find lineage os for j7 nxt ? ( android pie )

**Comment by dariotrombello** [comment]
XDA-Developers
